// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CrationdecompteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void crationdecompte() {
    driver.get("https://www.jumia.com.tn/");
    driver.manage().window().setSize(new Dimension(816, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.cssSelector(".-hr-bb > .btn")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("inesmaz.zz@gmail.com");
    driver.findElement(By.cssSelector(".access-btn > .mdc-button__touch")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("password")).sendKeys("aze123");
    {
      WebElement element = driver.findElement(By.cssSelector(".confirm-password-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("confirm-password-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#card_password > .fields:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".confirm-password-input")).sendKeys("aze123");
    driver.findElement(By.cssSelector(".to-personal-details > .mdc-button__touch")).click();
    driver.findElement(By.id("input_first_name")).click();
    driver.findElement(By.id("input_first_name")).sendKeys("ines");
    driver.findElement(By.id("input_middle_name")).click();
    driver.findElement(By.id("input_middle_name")).sendKeys("mas");
    driver.findElement(By.id("input_last_name")).click();
    driver.findElement(By.id("input_last_name")).sendKeys("mas");
    driver.findElement(By.name("phone[number]")).click();
    driver.findElement(By.name("phone[number]")).sendKeys("21240226");
    driver.findElement(By.cssSelector(".to-personal-details-part-2 > .mdc-button__touch")).click();
    driver.findElement(By.cssSelector("#gender > .mdc-select__anchor")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mdc-menu-surface--open .mdc-list-item:nth-child(2) > .mdc-list-item__text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mdc-menu-surface--open .mdc-list-item:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".mdc-menu-surface--open .mdc-list-item:nth-child(2)")).click();
    driver.findElement(By.id("input_birth_date")).click();
    driver.findElement(By.id("input_birth_date")).click();
    driver.findElement(By.id("input_birth_date")).sendKeys("2004-06-11");
    driver.findElement(By.cssSelector(".to-verification-code > .mdc-button__touch")).click();
    driver.findElement(By.cssSelector("#pin > .mdc-text-field:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("1");
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("2");
    driver.findElement(By.cssSelector("#pin > .mdc-text-field:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("3");
    driver.findElement(By.cssSelector(".mdc-text-field--focused")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("4");
    driver.findElement(By.cssSelector("#pin > .mdc-text-field:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("5");
    driver.findElement(By.cssSelector("#pin > .mdc-text-field:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("6");
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("1");
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("2");
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("3");
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("4");
    {
      WebElement element = driver.findElement(By.cssSelector(".mdc-text-field--focused"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".mdc-text-field--focused")).click();
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).sendKeys("5");
    driver.findElement(By.cssSelector(".mdc-text-field--focused > .mdc-text-field__input")).click();
    driver.findElement(By.cssSelector(".mdc-button__touch")).click();
  }
}
